CREATE TABLE BRAND
(
    BRAND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT
(
    PARTNUMBER VARCHAR(255) PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL
);

CREATE TABLE CURRENCY
(
    CURR        VARCHAR(3) PRIMARY KEY,
    NUM         VARCHAR(10)  NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LOCATION    VARCHAR(255) NOT NULL
);

CREATE TABLE PRICE_RATE
(
    PRICE_RATE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL
);

CREATE TABLE OFFER
(
    OFFER_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   BIGINT         NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRICE_LIST BIGINT         NOT NULL,
    PARTNUMBER VARCHAR(255)   NOT NULL,
    PRIORITY   INT            NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (BRAND_ID),
    FOREIGN KEY (PRICE_LIST) REFERENCES PRICE_RATE (PRICE_RATE_ID),
    FOREIGN KEY (PARTNUMBER) REFERENCES PRODUCT (PARTNUMBER),
    FOREIGN KEY (CURR) REFERENCES CURRENCY (CURR)
);
